services:
  # FastAPI backend (API only)
  research-api:
    image: ghcr.io/${GITHUB_OWNER}/${GHCR_REPOSITORY}:latest
    container_name: research_api_prod
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # App config
      - PORT=8000
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(5); s.connect(('127.0.0.1', 8000)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Celery worker (background tasks)
  worker:
    image: ghcr.io/${GITHUB_OWNER}/${GHCR_REPOSITORY}:latest
    container_name: research_worker_prod
    command: celery -A app.worker.celery_app worker --loglevel=info --concurrency=1
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    env_file:
      - .env
    environment:
      # Celery config
      - C_FORCE_ROOT=true  # Allow running as root (Docker container)
    restart: unless-stopped
    depends_on:
      - research-api
    healthcheck:
      test: ["CMD", "celery", "-A", "app.worker.celery_app", "inspect", "ping"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (API only)
  nginx:
    image: nginx:alpine
    container_name: research_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - /home/ec2-user/frontend:/var/www/frontend:ro
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    depends_on:
      - research-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/nginx-health"]
      interval: 5s
      timeout: 1s
      retries: 1
      start_period: 10s

networks:
  default:
    name: research_network_prod
